### ISSUE TITLE
I google useplatformtick come here

### ISSUE THREAD

**Issue by CiHel** [loopy750/Windows-Input-Lag-Analysis#1]
sorry for my bad english

excusme,your no set useplatformtick(default is no i think)?

if useplatformtick set yes timer resolution will be integer values 

this test is amazing

thank you spend a lot of time test and share
---btw---
many people just say using bcdedit /set useplatformtick yes

https://www.overclock.net/forum/375-mice/1742922-win-10-1909-bcdedit-set-useplatformtick-yes-causes-input-lag.html

 a guy say not good for 1909
---btw---

**Comment by loopy750** [comment]
I do not use useplatformtick yes, performance is worse for my PC. I use default. You can test for your PC but I recommend using the defaults (/deletevalue useplatformtick).

![attachment](https://user-images.githubusercontent.com/35911135/76957341-b9541780-6969-11ea-824b-bd15ae3a02b6.png)

I have compiled some data with Yes vs Default, and I might put together something better here with the tweaks I use and what each one does, when Windows 10 2004 is released.

**Comment by CiHel** [comment]
wow that is you
thank you add fps value
